module.exports = {
  loginForm: '.tw-login-form-container__stack',
  emailTextbox: 'input[name=\'email\']',
  passwordTextbox: 'input[name=\'password\']',
  loginBtn: 'button .tw-button__main-container',
  loginState: '.tw-sub-layout__content',
  newProjectText: '.tw-new-project-button-box__text',
  newProjectBtn: '.tw-new-project-button-box',
  newProjectModal: '.tw-modal__content',
  projectNameField: 'input[name="project-name"]',
  projectDescField: 'input[name="description"]',
  newProjectModalNextBtn: '.ax-new-project-choose-workflow-button',
  newProjectModalBackBtn: '.tw-choose-workflow__back',
  createProjectBtn: '.ax-create-project-button',
  createTasklist: '.tw-pre-created-tasklist',
  tasklistTitle: 'input[placeholder="Tasklist title"]',
  addTaskBtn: '.ax-add-task-button>i',
  taskTextfield: 'section.tw-task-input-panel',
  addTask: '.ax-task-input-panel-textfield',
  createTaskBtn: 'button.ax-create-task-button',
  createdTask: '.tw-task__main',
  taskProperties: '.tw-task-properties',
  closeBtnTaskProperties: '.ax-floating-panel-close',
  completeCheckbox: '.tw-task-header__checkbox',
  taskCompleteText: '.tw-task-date>span',
};
